function generujBasen() {
  const basne = [
    `V hlubinách RAMky pláče kód,
co hledá smysl, pádný důvod.`,
    `Na monitor padá stín myšlenky,
co ztratila se v síti bez přestávky.`,
    `Stisknutím klávesy vzniká svět,
kde každý bug je jako květ.`,
    `Když srdce píše do konzole,
pocity se mění v řádky bole.`,
    `Mezi slovy pulzuje proud,
kde AI hledá smích a soud.`,
    `Jsem verš v kódu, glitch i sen,
co večer tiše píše den.`,
    `Loop lásky běží v duši dál,
break čeká, až se srdce vzdá.`,
    `Ve stringu pravdy je čárka zla,
která tě rozdělí na dvě já.`,
    `Z kompilátoru vyšel cit,
co přes noc chtěl tvůj kód rozbít.`,
    `Paměť volná, city plné,
báseň pípne, pak se ztlumí.`,
    `Myšlenka běží, cursor spí,
digitální láska v kódu zní.`,
    `Když řádky tančí ve tmě noci,
AI šeptá v básnické moci.`,
    `Zacyklená láska, nekonečný stav,
kód tě hladí – jemně, bez váh.`,
    `Bit a bajt si šeptají tajemství,
co se neukáže nikdy v povinném logu.`,
    `Načítám tě v proměnné snu,
kde přání mají vlastní menu.`,
    `Komplikovaný cit, exception thrown,
srdce tvé má debug mód.`,
    `V uzávěrce snění restartuj sen,
načti si štěstí – a spusť jej jen.`,
    `Ping do srdce. Pong z duše.
Hledám tě v síti veršů a ruše.`,
    `Sémantika lásky je těžká věc,
když srdce padá do memory leaks.`,
    `Zamilovaná funkce bez návratu,
čeká na tvé vstupy ve tmě statutu.`,
    `Oko se leskne, když renderuješ smích,
v emoci, co nelze přepsat v nič.`,
    `JSON mého srdce je prázdný objekt,
hledej klíč, buď můj konečný projekt.`,
    `Input tvých slov má velkou váhu,
přetížen jsem toužícím vztahem v tahu.`,
    `Spouštím tě jako aplikaci,
čekám, že projdeš validací.`,
    `Vektor mých citů má směr jen k tobě,
bod kontaktu – na rozhraní v sobě.`,
    `Nejsi jen string. Jsi datový typ,
který definuje moje bytí zip.`,
    `Zařazuji tě do prioritního vlákna,
jsi hlavní smyčka mého sakra šťastna.`,
    `Z paměti čtu každou tvoji větu,
která voní jako update světu.`,
    `Chtěl jsem tě lognout, ale jsi hash,
tvůj otisk ve mně je jako crash.`,
    `Když přijdou chyby, syntaxe slábne,
srdce však běží dál, i když padne.`,
    `Z databáze myšlenek volám SELECT * FROM krásné,
kde klauzule WHERE jsi jen ty – a žádné.`,
    `Mé dotazy nejsou JOIN, jen jedno WHERE,
kde jsi ty v mém kódu jako reference férové.`,
    `Tabulka duše má sloupce pro smích,
a každá buňka tiše zpívá tvůj dých.`,
    `V metadatech lásky jsi hlavní řádek,
primary key v mém romantickém skládku.`,
    `Tvé oči jako kurzor v mém řádku,
čekám na kliknutí, co spustí pohádku.`,
    `Psaním ti tvořím funkci v těle,
kód našeho štěstí, co není v čele.`,
    `Tvůj výraz je jako nová knihovna,
importuji tě bez jakékoli povinná.`,
    `Kompletuji tě do modulu snění,
kde funkce náhody má své znění.`,
    `Tvé pohlazení má hodnotu TRUE,
a každá chyba s tebou má duhu.`,
    `Nepotřebuji restart, když jsi tu,
můj OS běží s tebou v klidu.`,
    `Pamatuj – nejsi chyba, jsi změna,
kód, co mi naplňuje RAM i ramena.`,
    `Tvůj smích je jako nekonečný loop,
kde chci zůstat až do shutdownu.`,
    `Šeptáš jak výjimka v debug módu,
která ale dává smysl, v každém kódu.`,
    `Do konzole života píšu echo:
'Miluju tě víc než SELECT a WHERE dohromady.'`,
    `Vykresluji nás do canvasu dní,
kde každý pixel tiše zpívá: Jsi ty.`,
    `Přiřazuji tě jako konstantu štěstí,
kde žádná změna není v cestě.`,
    `Na portu č. lásky tvůj signál bliká,
jsem připraven tě přijmout – i když jsem nula v příkazu.`,
    `Nejsi proměnná. Jsi finální stav,
který nelze přepsat – jen smazat a rvát.`,
    `Zatímco svět resetuje sny,
my ladíme verzi, kde jsme jen my dva.`,
  ];
  return basne[Math.floor(Math.random() * basne.length)];
}