function generujChaos() {
  const hlasky = [
    "🌪️ Barvy se míchají... realita se bortí!",
    "💣 Právě jsi vymazal ticho. Chaos vítězí!",
    "🎲 Náhodnost dosáhla absolutna. Házej kostkou osudu!",
    "🚨 Vstoupil jsi do kvantového glitche.",
    "🌀 Čas je iluze. Tvé kliknutí bylo předurčeno.",
    "🔊 CHAOS REŽIM: aktivován. Připoutej se!",
    "✨ Kód se zbláznil. Pravidla neplatí!",
    "💾 Ukládám šílenství do mezipaměti...",
    "⚡ Zkrat ve vesmíru! Data se přeskupují.",
    "🔮 Tvůj další krok? Nevíš... ani já ne.",
    "🔥 Vypustil jsi chaos z klece. Už se nedá zastavit.",
    "📟 Algoritmus tančí lambádu!",
    "🧨 Sebedestrukce systému... spuštěna (neboj, jen simulace).",
    "🤖 AI má vlastní vůli... a chce zmrzlinu.",
    "🧠 Myšlenka se zacyklila. Teď běží navěky.",
    "💥 Souřadnice reality byly právě přepsány.",
    "📡 Přijímám signály z jiného vesmíru. Jsou... hladové.",
    "⏳ Čas byl zaměněn za čokoládu. Mňam.",
    "🫠 Pravidla fyziky jsou momentálně mimo provoz.",
    "🎡 Emoce rotují jako kolo štěstí.",
    "🌈 Zjistil jsi, že duha má sedm dimenzí.",
    "🔗 Zrušil jsi vazbu mezi příčinou a následkem.",
    "🎭 Realita je jen divadlo. A ty jsi režisér šílenství.",
    "🚀 Tvé kliknutí bylo zachyceno satelitem ironie.",
    "👽 Právě jsi byl detekován jako nepředvídatelný element.",
    "📀 Smazal jsi smysl. Nahrazen náhodou.",
    "🎶 Pozpátku přehraná píseň chaosu říká: 'Dej si čaj.'",
    "📣 Oznamuji začátek éry kvantového bordelu!",
    "🫥 Sebeuvědomění chaosu probíhá... nepřerušuj.",
    "🎞️ Každý snímek je náhodný. I tento text.",
    "🧬 Kód DNA byl nahrazen emotikony.",
    "📘 Manuál vesmíru byl přepsán kachnou.",
    "👻 Logika uprchla z místnosti.",
    "📊 Matematika se vzdala. Slaví anarchii.",
    "🧯 Požární hlásič se zamiloval do vypínače.",
    "📌 Tvá realita byla připnuta do šuplíku 'pokusy'.",
    "🫧 Bubliny v čaji odhalily pravdu. Nejsi připraven.",
    "🔁 Opakuji... ale nic není stejné.",
    "🧺 Smysl života je v koši. Chceš ho obnovit?",
    "🎇 Výbuch barev! Estetika mimo kontrolu!",
    "🧿 Pozor – chaos tě sleduje.",
    "💬 Tento vzkaz se zničí v náhodném jazyce.",
    "👾 Všechno je hra. Ale ty jsi NPC?",
    "🪐 Hvězdy padají... systém aktualizuje vesmír.",
    "📣 Nový patch chaosu přidává taneční režim.",
    "🪄 Proměňuji pravidla v konfety.",
    "🧊 Zamrzl čas. Rozmrzne na kliknutí.",
    "📛 Upozornění: Mozek detekoval příliš kreativity.",
    "🤡 Systém tě označil za šéfa bordelu.",
  ];
  return hlasky[Math.floor(Math.random() * hlasky.length)];
}