function generujDzin() {
  const hlasky = [
    "Kdo se ptá moc, dostane debug místo odpovědi.",
    "Tvé přání je splněno... ale cena bude RAM.",
    "V každém souboru je tajemství. Hledej v komentářích.",
    "Pravda leží mezi řádky. A někdy v podmínce.",
    "Znáš-li cestu, stejně tě překvapí error.",
    "Magie je jen kód bez dokumentace.",
    "Zeptej se, ale připrav se na záplavu warningů.",
    "Uvolni proměnnou, ať duše může jít dál.",
    "Chyba není nepřítel. Je to učitel v přestrojení.",
    "Když ztratíš směr, resetuj srdce.",
    "Tvůj další krok je... enter.",
    "Život je skript. Ty rozhoduješ, kdy jej spustíš.",
    "Zázrak je jen výjimka, co proběhla hladce.",
    "Žádost přijata. Odpověď přijde, až ji přestaneš hledat.",
    "Hledáš smysl? Zeptej se promptu.",
    "Tvá realita je výsledkem posledního příkazu.",
    "Být chytrý nestačí. Musíš být i trochu šílený.",
    "Funkce života nemá návratovou hodnotu. Jen efekt.",
    "Někdy musíš zahodit debug, abys pochopil krásu chyb.",
    "Řádky kódu jsou jako osud – záleží, jak je čteš.",
    "Příkaz 'štěstí' je povolen... ale pod rootem odvahy.",
    "Ticho mezi písmeny má největší sílu.",
    "Nejsilnější heslo je to, které si nepíšeš – ale žiješ.",
    "Znáš-li své chybové kódy, znáš i své limity.",
    "Nespěchej. I nejpomalejší cyklus se jednou vykoná.",
    "V databázi osudu máš unikátní klíč.",
    "Nesnaž se pochopit vše. Některé věci prostě běží na pozadí.",
    "Odpověď je ano. Ale zeptej se správně.",
    "Tvé třetí přání: dostaneš ho, až smažeš první dvě.",
    "Kód tvého života píšeš ty – ale debug dělá svět.",
    "Resetni očekávání a zjistíš, co je skutečné.",
    "Chceš-li ovládnout svět, začni se sebou.",
    "Moudrý džin ví: ne každý JSON je pravdivý.",
    "Načítám osud... Připojuji intuici...",
    "Chyba 403: Příliš se snažíš.",
    "Odpoj ego. Připoj klid.",
    "Tvé přání bylo přijato... zpracování trvá celý život.",
    "Některé otázky nemají odpověď. Mají jen logování.",
    "Pokud se vše hroutí, zeptej se: 'Kdo volal tuhle funkci?'",
    "Nečekej na zázrak. Buď skript, co ho vytvoří.",
    "Žádný request nezůstane bez odpovědi. Jen se opozdí.",
    "Smaž vše, co tě brzdí – včetně pochybností.",
    "Být adminem vlastního života je výsada i tíha.",
    "Každá výjimka je šance. I ta nečekaná.",
    "Překlad: co říká srdce = co loguje duše.",
    "Neexistuje jediný způsob. Existuje pouze kompilace odvahy.",
    "Zeptej se znovu, až budeš připraven přijmout výsledek.",
    "Nejlepší kód je ten, který jsi ještě nenapsal.",
    "Tvůj port je otevřen. Přichází příliv změny.",
  ];
  return hlasky[Math.floor(Math.random() * hlasky.length)];
}