function generujFilozofku() {
  const hlasky = [
    "Smysl života je ukryt v síťovém kabelu, hned vedle smyslu pro humor.",
    "Když padne rohlík na zem máslem dolů, znamená to, že máš špatný BIOS.",
    "Mysl je jako RAM – když je plná blbostí, nic se nespustí.",
    "I největší bug v životě začíná v hlavě.",
    "Ptáš-li se, kdo jsi – zkontroluj si logy.",
    "Meditace je restart systému duše.",
    "Když nevíš kam dál, stiskni F5. Možná se obnovíš.",
    "Ve vesmíru je spousta hluku – a pak přijdeš ty a rozbiješ ticho větou o guláši.",
    "Nejsi zmatený. Jen žiješ ve světě bez návodu.",
    "Když nic neděláš, děláš to nejlíp – podívej se na mrak.",
    "Každý má svůj bug. Ale jen někteří ho pojmenovali vztah.",
    "Jestli tě život kopne do zadku, je to signál k upgradu.",
    "Včera jsi byl šťastný. Dnes jsi online. Náhoda?",
    "Moudrost začíná tam, kde se ztratí signál.",
    "Přemýšlej, než přemýšlíš – jinak se zacyklíš.",
    "Život je jako složený if. Když nevíš, kde jsi, jsi v else.",
    "Chceš odpověď? Nejprve vymaž cache své mysli.",
    "Nejsi pomalý. Jen běžíš v debug módu.",
    "Zrcadlo je jen přirozená forma selfie.",
    "Láska je, když ti někdo hackne srdce a ty ho ještě pozveš dál.",
    "Když ztratíš směr, zeptej se GPS. Nebo babičky.",
    "Nepotřebuješ Google. Potřebuješ guláš.",
    "Štěstí je jako Wi-Fi – někdy nejsilnější tam, kde ho nečekáš.",
    "Být offline neznamená být ztracený. Znamená to být naživu.",
    "Problémy se neřeší. Problémy se přeinstalují.",
    "Směj se, dokud ti nezamrzne RAMka.",
    "Největší databáze moudrosti je babiččin receptář.",
    "Když ti někdo řekne „buď sám sebou“, nevědí, co tím riskují.",
    "Každý den je nový řádek ve tvém osobním logu.",
    "Mozek máš jen jeden. A přesto ho sdílíš se sociálními sítěmi.",
    "Myšlenka bez činu je jako .exe bez přístupových práv.",
    "Zítra začnu... slavná poslední slova každého procesoru.",
    "Když život spadne, zkontroluj, jestli máš zálohu.",
    "Někdy je největší moudrost dát si pauzu a čaj.",
    "Nejsi líný. Jsi energeticky efektivní.",
    "Realita je to, co zbyde, když vypneš internet.",
    "Přemýšlíš moc. Zkus restart s kávou.",
    "Když tě všechno štve, napiš si vlastní příběh.",
    "Ne každá chyba je špatná. Některé vedou k upgrade.",
    "Dnes nečekej zázrak. Buď zázrakem ty.",
    "Čím víc dat, tím větší bordel. Tím víc života.",
    "Dobrý den začíná špatnou Wi-Fi a dobrou náladou.",
    "Zeptej se sebe, jestli fakt potřebuješ další cookies.",
    "Jestli jsi ztracený, možná jsi jen v jiné síti.",
    "Není chyba být mimo. Chyba je zůstat tam naschvál.",
    "Ticho je jen loading obrazovka vesmíru.",
    "Život je jako skript – může se spustit jakkoli.",
    "Programuj svůj den jako nejhezčí aplikaci.",
    "Nedělej všechno správně. Dělej to s radostí.",
    "Svět se nezbláznil. Jen je to nová verze reality.",
  ];
  return hlasky[Math.floor(Math.random() * hlasky.length)];
}