function generujKachnu() {
  const hlasky = [
    "Kvák! Jsem banán. Přijmi mě takového, jaký nejsem.",
    "Letící koberec právě požádal o občanství v ledničce.",
    "Když život dává citrony, hoď po něm kachnu.",
    "Moje levé křídlo má Wi-Fi. Pravé má chuť na perník.",
    "Stiskni tlačítko a získáš dočasné kachní osvícení.",
    "Rohlikologie je věda o tom, proč je máslo vždy dole.",
    "Pískám si hymnu chaosu při každém kávovém rituálu.",
    "Kachní král tě zve na sraz s veverkou z osmé dimenze.",
    "Pokud čteš tuto větu, právě tě hackla ryba.",
    "Zítra bude pondělí. Ale jen na Marsu a v Olomouci.",
    "Houska v kapse = univerzální klíč ke štěstí.",
    "Můj stín zpívá operu, když nikdo nekouká.",
    "Při východu slunce tančím s hologramem mývala.",
    "Věříš v osud, nebo jen v párek v rohlíku?",
    "Když slepice zakváká, je čas vypnout realitu.",
    "Existuje 11. smysl – najít ponožku v bubnu osudu.",
    "Každý ping má svůj pong, ale málokterý má sýra.",
    "Chceš pravdu? Počkej, až spadne toustovač z nebe.",
    "Dnes tě čeká cesta do podvědomí... skrz marmeládu.",
    "Náhodný fakt: kachny neumí lítat zpět v čase. Zatím.",
    "Písknutím aktivuješ starodávné siločáry humbuku.",
    "Myšlenka dne: Co když je realita jen špatný překlad?",
    "Pozor! Kachní zrcadla odráží myšlenky opačně.",
    "Neboj se absurdna. V něm bydlí skutečný smysl.",
    "Když ti prší do čaje, usměj se – možná je to signál.",
    "Každá duha je vlastně kódovaný kachní smích.",
    "Žádost o restart podána. Kachna schválila.",
    "Neexistuje chyba. Jen kachní test reality.",
    "Když najdeš ve špajzu kompas, jsi na správné cestě.",
    "Nejsi blázen. Jsi kachní prorok.",
    "Vtip bez pointy je jako kachna bez kvákání.",
    "Někdy musíš letět dolů, abys pochopil výtah.",
    "Ponožky v mikrovlnce nejsou řešení. Ale jsou teplé.",
    "Když nevíš, zeptej se nejbližšího sendviče.",
    "Den začíná nejlíp s kachnou na čele.",
    "Medvěd mi právě poslal email. Předmět: banán.",
    "Kachní pravda: ticho je jen hudba bez not.",
    "Máš právo na blbost. Ale používej ji moudře.",
    "Zrcadlo řeklo: 'Máš hezký chaos dneska.'",
    "Buď jako toast – křupavý, teplý a oblíbený.",
    "Jsi víc než součet tvých ponožek. Věř si!",
    "Když tě chytne melancholie, zatancuj s vysavačem.",
    "V každé ledničce je tajný portál do absurdna.",
    "Kachna ti radí: nikdy nejez vlaštovku pozpátku.",
    "Tvoje aura dnes připomíná citrusový glitch.",
    "Realita je jen dočasný bug ve tvém snění.",
    "Mysli jako vafle. Buď čtvercový, ale s chutí.",
    "Zvaž reboot světa. Začni s mazáním budíku.",
    "Když ti život podrazí nohy, odpověz breakdancem.",
  ];
  return hlasky[Math.floor(Math.random() * hlasky.length)];
}