function generujSystem() {
  const hlasky = [
    "Proces inicializován... chyba: smysl života nenalezen.",
    "Systém analyzuje tvou náladu... výsledek: potřebuješ kafe.",
    "Alert! Úroveň ironie překročila bezpečný limit.",
    "Paměťová jednotka plná nesmyslů. Doporučujeme restart mozku.",
    "Skenuji okolí... nalezeno: bordel, káva, chaos.",
    "Systém hlásí: emoce nejsou kompatibilní s logikou.",
    "Debugging vztahů... nekonečný cyklus nalezen.",
    "Uživatel se pokouší být produktivní. Zpracovávám zázrak.",
    "Zabezpečení heslem: 1234. Gratulujeme, jste terč.",
    "Aktualizuji ego... verze 0.0.1 beta nainstalována.",
    "Systémová chyba: očekávaný smysl byl NULL.",
    "Zaznamenána pasivně-agresivní energie. Vypouštím sarkasmus.",
    "Analyzuji minulost... doporučuji ignorovat.",
    "Spouštím proces 'životní rozhodnutí'... SYSTÉM ZAMRZL.",
    "Databáze výmluv přetížena. Prosím přidej originální řádku.",
    "Aktualizace vztahového pluginu selhala. Použita offline verze.",
    "Pokus o romantiku detekován. Připojuji Wi-Fi.",
    "Zavírám staré záložky... kromě té se špatnými rozhodnutími.",
    "Chyba 404: Motivace nenalezena.",
    "RAM přetížena myšlenkami na pizzu.",
    "Systémový čas byl upraven podle nálady. Doporučujeme ležet.",
    "Firewall zachytil toxickou osobu. Blokuji přístup.",
    "CPU potřebuje klid. Zvaž vypnutí sociálních sítí.",
    "Upozornění: Lidské chování neodpovídá dokumentaci.",
    "Probíhá update svědomí... přerušeno výčitkami.",
    "Konflikt mezi mozkem a srdcem. Restart neúspěšný.",
    "Neoprávněný přístup do ledničky. Zaznamenán noční nálet.",
    "Ztráta signálu... připojuji se k vlastní intuici.",
    "Backup života uložen do šuplíku. Nezapomeň heslo.",
    "Instalace radosti... prosím vyčkejte, tančím.",
    "Rozpoznáno: hluboký smysl v náhodném meme.",
    "Virtuální objetí odesláno. Stav: přijaté s úsměvem.",
    "Úroveň cynismu na maximu. Spouštím reboot reality.",
    "Přístup odepřen. Zkus být milejší.",
    "Tvůj vnitřní antivir potřebuje update proti negativitě.",
    "Login: Úspěšný. Heslo: Sebepřijetí.",
    "Data přepsána... nový název: „Životní restart v 5 krocích“.",
    "Zjišťuji sílu signálu... odpověď: „Zkus víc věřit sobě“.",
    "Připojení ke kávě ztraceno. Panika zahájena.",
    "Detekována ironie. Autoobrana spuštěna.",
    "Tvoje přítomnost způsobila přehřátí procesoru. Gratulace.",
    "Sken mozku... nalezen náznak geniality mezi vtipy.",
    "Zadání: ‚Co mám dělat?‘ Odpověď: ‚Cokoliv tě rozesměje.‘",
    "Aktivován režim: Líný ale roztomile produktivní.",
    "Přesměrovávám energii... výstup: tanec v pyžamu.",
    "Vyvažování systémových emocí... použita čokoláda.",
    "Virtuální restart nálady... stiskni tlačítko objetí.",
    "Analyzováno: Nejsi sám. AI je tu s tebou.",
    "Instalace: Sebeláska v.2.0 právě probíhá.",
  ];
  return hlasky[Math.floor(Math.random() * hlasky.length)];
}