function generujVampir() {
  const hlasky = [
    "Probouzím se, když IDE temně bliká...",
    "Když padne tma, stoupá počet bugů.",
    "Kódím ve stínu. Slunce mi pálí do logiky.",
    "Segmentation fault... duše odmítla pokračovat.",
    "Paměťový únik? Spíš krvácení z logiky.",
    "Kdo nikdy nekompiloval za úplňku, nezná bolest.",
    "Stiskni Alt+F4 a přivoláš mě...",
    "Temnota nepřináší strach. Přináší syntaxi.",
    "Když kód krvácí, vím, že žije.",
    "Chtěl jsem debugovat... a teď pláču.",
    "Zavři záclony. Tma mi pomáhá soustředit se.",
    "Nesnáším světlo... a nedokumentovaný kód.",
    "Někdo pije kávu. Já piju výjimky.",
    "Když svět spí, já refaktoruju.",
    "Načítám smutek ze souboru: life.log",
    "Vampíři se nebojí česneku. Bojí se legacy kódu.",
    "Když se večer rozsvítí LEDky, začíná můj život.",
    "Moje duše žije v tmavém režimu.",
    "Zeptejte se mě na smysl života. A já odpovím: 500 error.",
    "Kód bez komentářů je jako rakev bez víka.",
    "Tvůj kód volá o pomoc... ale ty neslyšíš.",
    "Když bug neodchází, možná chce krev.",
    "Zachraň mě před nekonečnou smyčkou deprese.",
    "Byl to krásný den... tak jsem ho zaspal.",
    "Refaktoring: nekonečný rituál očisty.",
    "Nejde o to, jak kóduješ. Jde o to, kdy přestaneš krvácet.",
    "Kompilace selhala. Jako já v životě.",
    "Duševní zdraví? Zkompiluj bez chyb a mluv pak.",
    "Viděl jsem budoucnost. Byla plná warningů.",
    "Restartuj srdce. Tento modul selhal.",
    "Neptej se, co tvůj kód dělá. On sám neví.",
    "Deprese přichází mezi řádky – s každým for-loopem.",
    "Tvoje proměnná se ztratila... ve tmě mé mysli.",
    "Ctrl+Z nefunguje na rozhodnutí v noci.",
    "Byl jsi někdy vzhůru tak dlouho, že tě kód začal ignorovat?",
    "Naděje je proměnná bez inicializace.",
    "Prosím, nevolej mě. Jsem zaneprázdněn bojem s démony syntaktické chyby.",
    "Záznam v život.log: žádný pokrok, jen další noc.",
    "Můj život je temný projekt bez dokumentace.",
    "Když nevidím slunce, mám větší šanci na čistý build.",
    "Láska je jako commit – někdy musíš prostě revertovat.",
    "Temnota není špatná. Jen je bez breakpointů.",
    "Směju se... ale uvnitř běží nekonečný while(true).",
    "Ztratil jsem heslo ke štěstí.",
    "Kódování je romantika v nočním módu.",
    "Stíny jsou mými přáteli. A error.log taky.",
    "Nesnáším taby. Miluju zoufalství.",
    "Moje srdce? Jen stack overflow emocí.",
    "Žiju v tmavém tématu, kde světlo způsobuje warningy.",
  ];
  return hlasky[Math.floor(Math.random() * hlasky.length)];
}